# Generated by Django 4.0.5 on 2022-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='address')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='link')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('year', models.CharField(blank=True, max_length=250, null=True, verbose_name='year')),
                ('rooms', models.CharField(blank=True, max_length=250, null=True, verbose_name='rooms')),
                ('area', models.CharField(blank=True, max_length=250, null=True, verbose_name='area')),
                ('floor', models.CharField(blank=True, max_length=250, null=True, verbose_name='floor')),
                ('anbari', models.CharField(blank=True, max_length=250, null=True, verbose_name='anbari')),
                ('parking', models.CharField(blank=True, max_length=250, null=True, verbose_name='parking')),
                ('elevator', models.CharField(blank=True, max_length=250, null=True, verbose_name='elevator')),
                ('price_per_meter', models.CharField(blank=True, max_length=250, null=True, verbose_name='price_per_meter')),
                ('total_price', models.CharField(blank=True, max_length=250, null=True, verbose_name='total_price')),
                ('type_of_sell', models.CharField(blank=True, max_length=250, null=True, verbose_name='type_of_sell')),
                ('main_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='main_type')),
                ('sub_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='sub_type')),
                ('contact', models.CharField(blank=True, max_length=250, null=True, verbose_name='contact')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'ordering': ('id', 'created_date'),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='neighborhood'),
        ),
    ]
