# Generated by Django 4.0.5 on 2022-07-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_home_user_keywords_user_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('token', models.CharField(max_length=250, verbose_name='token')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'AppToken',
                'verbose_name_plural': 'AppTokens',
                'ordering': ('id', 'created_date'),
            },
        ),
    ]
