# Generated by Django 4.0.5 on 2022-07-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_neighborhood_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='price'),
        ),
    ]
