# Generated by Django 4.0.5 on 2022-07-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_searchwords_home_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptokens',
            name='token',
            field=models.CharField(max_length=1000, verbose_name='token'),
        ),
    ]
