# Generated by Django 4.0.6 on 2022-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='days_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='days_left'),
        ),
    ]
