# Generated by Django 4.0.6 on 2022-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
