# Generated by Django 4.0.6 on 2022-07-23 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_mainpayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpayed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainpayed', to=settings.AUTH_USER_MODEL),
        ),
    ]
