# Generated by Django 4.0.6 on 2022-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_mainpayed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='days_left',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='days_left'),
        ),
    ]
