# Generated by Django 4.0.6 on 2022-07-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_payments_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='days_left',
            field=models.IntegerField(blank=True, default=7, null=True, verbose_name='days_left'),
        ),
    ]
